---
services:
  init:
    command: /bin/sh /mnt/data/init.sh
    container_name: init
    depends_on:
      kafka:
        condition: service_healthy
    image: confluentinc/cp-kafka:7.6.2
    volumes:
      - "./tests/resources/init:/mnt/data"


  kafka:
    container_name: kafka
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_LISTENERS: 'INTERNAL://kafka:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      LOG_LEVEL: WARN
    healthcheck:
      test: kafka-topics --list --bootstrap-server kafka:9092
      interval: 1s
      retries: 30
    image: confluentinc/cp-kafka:7.6.2
    ports:
      - 9092:9092

  router:
    build:
      context: .
      tags:
        - router:latest
    container_name: router
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
      KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_CONSUMER_CLIENT_ID: kafka_router
      KAFKA_CONSUMER_ENABLE_AUTO_COMMIT: false
      KAFKA_CONSUMER_GROUP_ID: kafka_router_1
      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_ROUTER_DLQ_TOPIC_NAME: 'router.dlq'
      KAFKA_ROUTER_RULE_COUNTRY_IS_GB: '{"destination_topic":"GB.output.json","jmespath":"country","regexp":"^GB$","source_topic":"input.json"}'
      KAFKA_ROUTER_RULE_COUNTRY_IS_IE: '{"destination_topic":"IE.output.json","jmespath":"country","regexp":"^IE$","source_topic":"input.json"}'
      KAFKA_ROUTER_RULE_COUNTRY_UK_VAT_NUMBER: '{"destination_topic":"GB.output.json","jmespath":"vat_number","regexp":"^GB","source_topic":"input.json"}'
      KAFKA_ROUTER_RULE_COUNTRY_IE_VAT_NUMBER: '{"destination_topic":"IE.output.json","jmespath":"vat_number","regexp":"^IE","source_topic":"input.json"}'
      KAFKA_ROUTER_PROMETHEUS_PREFIX: "docker_"
      LOG_LEVEL: DEBUG
    ports:
      - 8000:8000
